[2025-04-09T13:10:51.197+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T13:10:51.229+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T11:35:23.843545+00:00 [queued]>
[2025-04-09T13:10:51.242+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T11:35:23.843545+00:00 [queued]>
[2025-04-09T13:10:51.243+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-09T13:10:51.266+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-04-09 11:35:23.843545+00:00
[2025-04-09T13:10:51.276+0000] {standard_task_runner.py:72} INFO - Started process 22162 to run task
[2025-04-09T13:10:51.286+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-04-09T11:35:23.843545+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp7pddkn0a']
[2025-04-09T13:10:51.288+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask is_weather_api_ready
[2025-04-09T13:10:51.345+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T11:35:23.843545+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T13:10:51.613+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T11:35:23.843545+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T11:35:23.843545+00:00'
[2025-04-09T13:10:51.615+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T13:10:51.615+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T13:10:51.616+0000] {logging_mixin.py:190} INFO - Current task name:is_weather_api_ready state:running start_date:2025-04-09 13:10:51.229730+00:00
[2025-04-09T13:10:51.616+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T13:10:51.616+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T13:10:51.617+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-09T13:10:51.617+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:10:51.623+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:10:51.711+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:10:51.711+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:11:51.720+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:11:51.722+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:11:51.804+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:11:51.805+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:12:51.805+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:12:51.808+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:12:51.917+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:12:51.917+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:13:51.918+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:13:51.921+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:13:52.008+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:13:52.009+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:14:52.010+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:14:52.013+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:14:52.104+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:14:52.104+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:15:52.105+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:15:52.112+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:15:52.212+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:15:52.212+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:16:52.213+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:16:52.216+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:16:52.320+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:16:52.321+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:17:52.322+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:17:52.324+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:17:52.433+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:17:52.433+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:18:52.434+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:18:52.437+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:18:52.542+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:18:52.542+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:19:52.543+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:19:52.550+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:19:52.649+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:19:52.650+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:20:52.651+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:20:52.653+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:20:52.753+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:20:52.753+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:21:52.754+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:21:52.757+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:21:52.852+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:21:52.852+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:22:52.853+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:22:52.855+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:22:52.956+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:22:52.956+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:23:52.957+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:23:52.960+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:23:53.066+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:23:53.066+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:24:53.067+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:24:53.070+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:24:53.172+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:24:53.173+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:25:53.177+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:25:53.194+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:25:53.303+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:25:53.304+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:26:53.305+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:26:53.308+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:26:53.389+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:26:53.390+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:27:53.395+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:27:53.425+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:27:53.533+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:27:53.534+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:28:53.539+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:28:53.543+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:28:53.626+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:28:53.627+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:29:53.628+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:29:53.636+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:29:53.739+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:29:53.739+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:30:53.740+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:30:53.743+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:30:53.839+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:30:53.840+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:31:53.841+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:31:53.844+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:31:53.937+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:31:53.937+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:32:53.938+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:32:53.941+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:32:54.045+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:32:54.045+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:33:54.046+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:33:54.049+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:33:54.150+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:33:54.150+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:34:54.151+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:34:54.154+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:34:54.240+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:34:54.241+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:35:54.241+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:35:54.246+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:35:54.331+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:35:54.331+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:36:54.332+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:36:54.335+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:36:54.421+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:36:54.421+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:37:54.422+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:37:54.427+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:37:54.510+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:37:54.511+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:38:54.511+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:38:54.516+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:38:54.616+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:38:54.616+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:39:54.617+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:39:54.621+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:39:54.728+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:39:54.728+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:40:54.729+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:40:54.733+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:40:54.831+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:40:54.832+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:41:54.833+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:41:54.835+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:41:54.925+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:41:54.925+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:42:54.931+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:42:54.942+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:42:55.049+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:42:55.049+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:43:55.054+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:43:55.057+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:43:55.182+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:43:55.182+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:44:55.183+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:44:55.186+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:44:55.278+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:44:55.278+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:45:55.279+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:45:55.282+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:45:55.388+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:45:55.388+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:46:55.390+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:46:55.401+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:46:55.492+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:46:55.493+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:47:55.496+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:47:55.499+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:47:55.597+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:47:55.597+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:48:55.598+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:48:55.601+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:48:55.689+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:48:55.689+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:49:55.690+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:49:55.693+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:49:55.779+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:49:55.779+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:50:55.784+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:50:55.804+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:50:55.907+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:50:55.907+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:51:55.913+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:51:55.916+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:51:55.999+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:51:56.001+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:52:56.003+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:52:56.006+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:52:56.097+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:52:56.097+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:53:56.098+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:53:56.103+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:53:56.197+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:53:56.198+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:54:56.199+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:54:56.202+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:54:56.287+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:54:56.287+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:55:56.288+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:55:56.296+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:55:56.381+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:55:56.382+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:56:56.383+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:56:56.388+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:56:56.476+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:56:56.476+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:57:56.477+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:57:56.483+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:57:56.571+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:57:56.572+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:58:56.573+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:58:56.576+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:58:56.658+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:58:56.659+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:59:56.659+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:59:56.663+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:59:56.748+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:59:56.748+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:00:56.749+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:00:56.752+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:00:56.831+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:00:56.832+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:01:56.833+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:01:56.836+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:01:56.921+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:01:56.922+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:02:56.922+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:02:56.928+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:02:57.016+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:02:57.016+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:03:57.017+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:03:57.020+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:03:57.104+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:03:57.104+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:04:57.105+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:04:57.108+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:04:57.186+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:04:57.187+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:05:57.188+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:05:57.194+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:05:57.288+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:05:57.288+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:06:57.289+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:06:57.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:06:57.383+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:06:57.385+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:07:57.386+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:07:57.389+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:07:57.492+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:07:57.493+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:08:57.493+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:08:57.497+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:08:57.596+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:08:57.596+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:09:57.597+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:09:57.600+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:09:57.709+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:09:57.709+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:10:57.712+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:10:57.715+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:10:57.825+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:10:57.825+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:11:57.826+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:11:57.830+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:11:57.933+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:11:57.933+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:12:57.934+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:12:57.937+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:12:58.037+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:12:58.037+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:13:58.038+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:13:58.048+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:13:58.169+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:13:58.169+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:14:58.170+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:14:58.174+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:14:58.272+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:14:58.273+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:15:58.273+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:15:58.276+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:15:58.374+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:15:58.375+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:16:58.376+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:16:58.379+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:16:58.485+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:16:58.485+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:17:58.486+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:17:58.489+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:17:58.587+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:17:58.588+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:18:58.588+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:18:58.593+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:18:58.696+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:18:58.697+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:19:58.698+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:19:58.701+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:19:58.805+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:19:58.806+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:20:58.807+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:20:58.810+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:20:58.900+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:20:58.901+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:21:58.902+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:21:58.905+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:21:58.992+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:21:58.993+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:22:58.994+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:22:58.996+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:22:59.096+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:22:59.097+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:23:59.098+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:23:59.108+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:23:59.201+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:23:59.202+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:24:59.202+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:24:59.209+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:24:59.300+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:24:59.300+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:25:59.301+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:25:59.304+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:25:59.389+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:25:59.389+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:26:59.390+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:26:59.394+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:26:59.482+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:26:59.483+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:27:59.484+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:27:59.487+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:27:59.567+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:27:59.567+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:28:59.568+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:28:59.571+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:28:59.660+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:28:59.660+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:29:59.661+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:29:59.664+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:29:59.748+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:29:59.749+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:30:59.749+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:30:59.754+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:30:59.840+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:30:59.841+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:31:59.841+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:31:59.845+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:31:59.931+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:31:59.931+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:32:59.932+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:32:59.935+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:33:00.042+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:33:00.043+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:34:00.043+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:34:00.047+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:34:00.127+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:34:00.127+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:35:00.128+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:35:00.131+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:35:00.218+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:35:00.218+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:36:00.219+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:36:00.222+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:36:00.312+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:36:00.312+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:37:00.313+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:37:00.316+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:37:00.400+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:37:00.401+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:38:00.401+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:38:00.404+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:38:00.501+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:38:00.502+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:39:00.503+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:39:00.508+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:39:00.610+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:39:00.610+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:40:00.611+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:40:00.614+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:40:00.705+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:40:00.705+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:41:00.707+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:41:00.710+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:41:00.804+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:41:00.804+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:42:00.805+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:42:00.808+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:42:00.911+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:42:00.911+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:43:00.912+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:43:00.916+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:43:01.021+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:43:01.021+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:44:01.022+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:44:01.026+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:44:01.112+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:44:01.113+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:45:01.114+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:45:01.117+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:45:01.202+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:45:01.202+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:46:01.203+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:46:01.206+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:46:01.290+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:46:01.290+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:47:01.291+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:47:01.297+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:47:01.382+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:47:01.382+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:48:01.383+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:48:01.386+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:48:01.470+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:48:01.470+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:49:01.471+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:49:01.477+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:49:01.578+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:49:01.578+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:50:01.579+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:50:01.583+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:50:01.668+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:50:01.668+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:51:01.669+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:51:01.672+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:51:01.774+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:51:01.775+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:52:01.776+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:52:01.779+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:52:01.880+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:52:01.881+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:53:01.882+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:53:01.886+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:53:01.983+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:53:01.984+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:54:01.985+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:54:01.988+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:54:02.092+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:54:02.092+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:55:02.093+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:55:02.096+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:55:02.196+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:55:02.196+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:56:02.197+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:56:02.202+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:56:02.321+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:56:02.321+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:57:02.322+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:57:02.326+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:57:02.427+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:57:02.428+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:58:02.428+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:58:02.431+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:58:02.534+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:58:02.534+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:59:02.535+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:59:02.538+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:59:02.643+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:59:02.643+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:00:02.644+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:00:02.647+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:00:02.740+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:00:02.741+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:01:02.741+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:01:02.745+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:01:02.837+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:01:02.838+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:02:02.841+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:02:02.847+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:02:02.950+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:02:02.951+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:03:02.951+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:03:02.961+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:03:03.069+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:03:03.070+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:04:03.071+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:04:03.075+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:04:03.162+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:04:03.163+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:05:03.167+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:05:03.181+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:05:03.280+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:05:03.281+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:06:03.282+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:06:03.285+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:06:03.365+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:06:03.366+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:07:03.366+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:07:03.369+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:07:03.455+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:07:03.456+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:08:03.457+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:08:03.461+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:08:03.544+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:08:03.544+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:09:03.545+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:09:03.552+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:09:03.636+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:09:03.636+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:10:03.637+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:10:03.640+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:10:03.729+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:10:03.729+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:11:03.732+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:11:03.735+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:11:03.817+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:11:03.818+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:12:03.818+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:12:03.825+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:12:03.911+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:12:03.911+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:13:03.912+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:13:03.921+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:13:04.028+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:13:04.028+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:14:04.029+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:14:04.032+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:14:04.132+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:14:04.133+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:15:04.134+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:15:04.139+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:15:04.244+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:15:04.244+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:16:04.245+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:16:04.248+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:16:04.342+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:16:04.342+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:17:04.343+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:17:04.348+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:17:04.433+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:17:04.434+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:18:04.434+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:18:04.440+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:18:04.527+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:18:04.527+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:19:04.528+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:19:04.531+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:19:04.617+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:19:04.617+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:20:04.618+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:20:04.621+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:20:04.712+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:20:04.713+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:21:04.713+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:21:04.716+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:21:04.810+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:21:04.811+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:22:04.812+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:22:04.814+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:22:04.909+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:22:04.909+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:23:04.910+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:23:04.915+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:23:05.014+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:23:05.014+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:24:05.019+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:24:05.025+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:24:05.129+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:24:05.129+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:25:05.130+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:25:05.136+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:25:05.237+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:25:05.238+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:26:05.239+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:26:05.243+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:26:05.332+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:26:05.332+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:27:05.333+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:27:05.337+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:27:05.422+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:27:05.423+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:28:05.423+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:28:05.428+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:28:05.519+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:28:05.519+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:29:05.520+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:29:05.523+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:29:05.608+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:29:05.608+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:30:05.609+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:30:05.618+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:30:05.708+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:30:05.710+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:31:05.711+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:31:05.714+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:31:05.798+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:31:05.798+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:32:05.799+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:32:05.802+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:32:05.908+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:32:05.908+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:33:05.909+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:33:05.916+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:33:06.024+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:33:06.024+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:34:06.025+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:34:06.031+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:34:06.135+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:34:06.135+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:35:06.137+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:35:06.150+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:35:06.242+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:35:06.242+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:36:06.243+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:36:06.246+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:36:06.329+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:36:06.330+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:37:06.330+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:37:06.334+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:37:06.419+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:37:06.419+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:38:06.421+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:38:06.424+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:38:06.513+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:38:06.514+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:39:06.514+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:39:06.519+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:39:06.598+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:39:06.598+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:40:06.599+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:40:06.604+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:40:06.689+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:40:06.689+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:41:06.690+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:41:06.693+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:41:06.776+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:41:06.778+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:42:06.779+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:42:06.783+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:42:06.869+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:42:06.869+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:43:06.870+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:43:06.873+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:43:06.979+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:43:06.979+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:44:06.981+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:44:06.984+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:44:07.078+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:44:07.078+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:45:07.079+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:45:07.083+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:45:07.175+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:45:07.176+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:46:07.177+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:46:07.179+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:46:07.284+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:46:07.284+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:47:07.286+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:47:07.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:47:07.388+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:47:07.389+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:48:07.390+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:48:07.393+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:48:07.488+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:48:07.489+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:49:07.489+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:49:07.492+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:49:07.579+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:49:07.580+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:50:07.581+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:50:07.585+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:50:07.686+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:50:07.686+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:51:07.687+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:51:07.690+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:51:07.784+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:51:07.785+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:52:07.785+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:52:07.790+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:52:07.892+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:52:07.893+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:53:07.894+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:53:07.897+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:53:07.998+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:53:07.999+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:54:08.000+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:54:08.002+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:54:08.092+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:54:08.093+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:55:08.093+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:55:08.099+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:55:08.181+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:55:08.182+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:56:08.183+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:56:08.186+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:56:08.286+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:56:08.286+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:57:08.287+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:57:08.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:57:08.394+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:57:08.394+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:58:08.395+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:58:08.399+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:58:08.498+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:58:08.498+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:59:08.499+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:59:08.502+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:59:08.602+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:59:08.603+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:00:08.604+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:00:08.606+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:00:08.704+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:00:08.704+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:01:08.705+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:01:08.708+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:01:08.794+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:01:08.794+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:02:08.795+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:02:08.798+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:02:08.878+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:02:08.878+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:03:08.879+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:03:08.883+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:03:08.985+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:03:08.986+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:04:08.990+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:04:08.999+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:04:09.099+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:04:09.099+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:05:09.101+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:05:09.104+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:05:09.189+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:05:09.190+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:06:09.191+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:06:09.193+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:06:09.289+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:06:09.290+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:07:09.290+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:07:09.294+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:07:09.383+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:07:09.383+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:08:09.384+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:08:09.388+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:08:09.487+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:08:09.488+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:09:09.489+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:09:09.492+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:09:09.591+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:09:09.591+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:10:09.592+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:10:09.597+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:10:09.700+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:10:09.700+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:11:09.701+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:11:09.705+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:11:09.804+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:11:09.804+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:12:09.805+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:12:09.808+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:12:09.909+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:12:09.909+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:13:09.911+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:13:09.916+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:13:10.002+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:13:10.002+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:14:10.003+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:14:10.015+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:14:10.103+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:14:10.104+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:15:10.105+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:15:10.107+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:15:10.198+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:15:10.198+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:16:10.200+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:16:10.204+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:16:10.297+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:16:10.297+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:17:10.298+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:17:10.304+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:17:10.394+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:17:10.396+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:18:10.397+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:18:10.401+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:18:10.484+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:18:10.485+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:19:10.486+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:19:10.490+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:19:10.572+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:19:10.573+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:20:10.574+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:20:10.578+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:20:10.662+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:20:10.662+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:21:10.666+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:21:10.670+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:21:10.762+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:21:10.763+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:22:10.764+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:22:10.770+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:22:10.851+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:22:10.852+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:23:10.853+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:23:10.856+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:23:10.944+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:23:10.944+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:24:10.947+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:24:10.959+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:24:11.048+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:24:11.048+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:25:11.049+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:25:11.053+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:25:11.139+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:25:11.139+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:26:11.140+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:26:11.143+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:26:11.241+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:26:11.242+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:27:11.243+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:27:11.247+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:27:11.334+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:27:11.335+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:28:11.336+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:28:11.339+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:28:11.423+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:28:11.423+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:29:11.425+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:29:11.428+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:29:11.521+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:29:11.521+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:30:11.522+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:30:11.524+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:30:11.605+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:30:11.605+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:31:11.606+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:31:11.611+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:31:11.700+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:31:11.701+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:32:11.702+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:32:11.706+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:32:11.787+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:32:11.787+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:33:11.790+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:33:11.794+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:33:11.882+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:33:11.882+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:34:11.884+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:34:11.887+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:34:11.989+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:34:11.990+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:35:11.991+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:35:11.997+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:35:12.106+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:35:12.107+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:36:12.108+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:36:12.114+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:36:12.202+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:36:12.203+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:37:12.204+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:37:12.208+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:37:12.287+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:37:12.288+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:38:12.289+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:38:12.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:38:12.382+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:38:12.382+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:39:12.383+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:39:12.386+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:39:12.496+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:39:12.496+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:40:12.497+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:40:12.500+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:40:12.583+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:40:12.583+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:41:12.584+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:41:12.587+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:41:12.686+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:41:12.686+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:42:12.687+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:42:12.690+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:42:12.785+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:42:12.786+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:43:12.786+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:43:12.790+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:43:12.888+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:43:12.889+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:44:12.889+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:44:12.899+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:44:12.996+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:44:12.996+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:45:12.997+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:45:13.000+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:45:13.104+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:45:13.104+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:46:13.105+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:46:13.111+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:46:13.197+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:46:13.197+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:47:13.198+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:47:13.202+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:47:13.298+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:47:13.298+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:48:13.299+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:48:13.307+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:48:13.410+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:48:13.411+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:49:13.412+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:49:13.415+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:49:13.519+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:49:13.519+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:50:13.523+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:50:13.535+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:50:13.649+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:50:13.649+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:51:13.650+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:51:13.653+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:51:13.745+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:51:13.746+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:52:13.747+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:52:13.754+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:52:13.846+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:52:13.846+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:53:13.848+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:53:13.850+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:53:13.930+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:53:13.930+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:54:13.931+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:54:13.934+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:54:14.014+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:54:14.014+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:55:14.018+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:55:14.025+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:55:14.111+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:55:14.111+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:56:14.112+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:56:14.115+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:56:14.204+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:56:14.204+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:57:14.205+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:57:14.212+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:57:14.298+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:57:14.298+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:58:14.299+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:58:14.302+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:58:14.391+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:58:14.392+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:59:14.393+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:59:14.396+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:59:14.476+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:59:14.476+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:00:14.477+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:00:14.480+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:00:14.565+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:00:14.565+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:01:14.566+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:01:14.569+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:01:14.668+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:01:14.668+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:02:14.669+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:02:14.672+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:02:14.773+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:02:14.773+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:03:14.774+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:03:14.777+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:03:14.877+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:03:14.878+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:04:14.878+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:04:14.883+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:04:14.985+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:04:14.985+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:05:14.987+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:05:14.994+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:05:15.102+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:05:15.103+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:06:15.104+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:06:15.108+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:06:15.200+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:06:15.200+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:07:15.201+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:07:15.204+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:07:15.289+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:07:15.289+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:08:15.290+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:08:15.294+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:08:15.384+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:08:15.384+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:09:15.386+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:09:15.390+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:09:15.474+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:09:15.475+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:10:15.476+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:10:15.481+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:10:15.576+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:10:15.577+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:11:15.578+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:11:15.580+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:11:15.679+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:11:15.679+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:12:15.680+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:12:15.684+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:12:15.783+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:12:15.783+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:13:15.784+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:13:15.787+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:13:15.883+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:13:15.883+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:14:15.884+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:14:15.889+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:14:15.986+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:14:15.986+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:15:15.987+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:15:15.992+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:15:16.088+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:15:16.089+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:16:16.089+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:16:16.092+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:16:16.197+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:16:16.197+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:17:16.198+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:17:16.201+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:17:16.292+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:17:16.292+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:18:16.293+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:18:16.296+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:18:16.398+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:18:16.398+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:19:16.399+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:19:16.404+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:19:16.504+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:19:16.505+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:20:16.506+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:20:16.509+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:20:16.603+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:20:16.604+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:21:16.605+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:21:16.608+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:21:16.713+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:21:16.713+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:22:16.714+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:22:16.717+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:22:16.817+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:22:16.817+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:23:16.818+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:23:16.823+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:23:16.924+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:23:16.925+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:24:16.926+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:24:16.929+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:24:17.035+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:24:17.039+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:25:17.040+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:25:17.042+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:25:17.138+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:25:17.138+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:26:17.139+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:26:17.143+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:26:17.245+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:26:17.246+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:27:17.249+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:27:17.251+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:27:17.345+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:27:17.346+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:28:17.347+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:28:17.352+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:28:17.453+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:28:17.453+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:29:17.459+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:29:17.470+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:29:17.587+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:29:17.587+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:30:17.592+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:30:17.596+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:30:17.693+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:30:17.693+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:31:17.694+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:31:17.697+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:31:17.782+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:31:17.783+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:32:17.784+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:32:17.788+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:32:17.873+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:32:17.873+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:33:17.874+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:33:17.882+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:33:17.968+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:33:17.968+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:34:17.969+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:34:17.973+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:34:18.076+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:34:18.077+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:35:18.078+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:35:18.081+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:35:18.182+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:35:18.182+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:36:18.183+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:36:18.186+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:36:18.286+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:36:18.287+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:37:18.287+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:37:18.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:37:18.395+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:37:18.395+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:38:18.399+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:38:18.403+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:38:18.505+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:38:18.506+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:39:18.506+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:39:18.509+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:39:18.589+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:39:18.590+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:40:18.590+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:40:18.593+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:40:18.680+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:40:18.680+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:41:18.681+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:41:18.687+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:41:18.782+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:41:18.783+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:42:18.784+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:42:18.787+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:42:18.868+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:42:18.868+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:43:18.869+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:43:18.875+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:43:18.958+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:43:18.958+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:44:18.960+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:44:18.967+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:44:19.053+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:44:19.054+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:45:19.054+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:45:19.058+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:45:19.142+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:45:19.143+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:46:19.144+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:46:19.147+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:46:19.234+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:46:19.234+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:47:19.240+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:47:19.243+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:47:19.322+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:47:19.322+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:48:19.323+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:48:19.326+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:48:19.415+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:48:19.415+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:49:19.416+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:49:19.419+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:49:19.505+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:49:19.505+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:50:19.506+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:50:19.509+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:50:19.599+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:50:19.599+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:51:19.600+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:51:19.605+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:51:19.697+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:51:19.698+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:52:19.699+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:52:19.702+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:52:19.783+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:52:19.783+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:53:19.784+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:53:19.787+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:53:19.873+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:53:19.874+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:54:19.874+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:54:19.878+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:54:19.972+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:54:19.973+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:55:19.973+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:55:19.977+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:55:20.060+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:55:20.060+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:56:20.061+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:56:20.064+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:56:20.153+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:56:20.153+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
