[2025-04-09T16:28:04.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T16:28:04.182+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T16:27:42.829062+00:00 [queued]>
[2025-04-09T16:28:04.190+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T16:27:42.829062+00:00 [queued]>
[2025-04-09T16:28:04.191+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-09T16:28:04.212+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2025-04-09 16:27:42.829062+00:00
[2025-04-09T16:28:04.222+0000] {standard_task_runner.py:72} INFO - Started process 32977 to run task
[2025-04-09T16:28:04.227+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2025-04-09T16:27:42.829062+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp90nujcew']
[2025-04-09T16:28:04.228+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask transform_load_weather_data
[2025-04-09T16:28:04.273+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2025-04-09T16:27:42.829062+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T16:28:04.348+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T16:27:42.829062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T16:27:42.829062+00:00'
[2025-04-09T16:28:04.350+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T16:28:04.350+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T16:28:04.350+0000] {logging_mixin.py:190} INFO - Current task name:transform_load_weather_data state:running start_date:2025-04-09 16:28:04.183354+00:00
[2025-04-09T16:28:04.351+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T16:28:04.351+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T16:28:04.357+0000] {logging_mixin.py:190} INFO - Data received:  {'coord': {'lon': -122.6762, 'lat': 45.5234}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'base': 'stations', 'main': {'temp': 283.06, 'feels_like': 282.05, 'temp_min': 281.41, 'temp_max': 284.45, 'pressure': 1024, 'humidity': 89, 'sea_level': 1024, 'grnd_level': 1014}, 'visibility': 10000, 'wind': {'speed': 2.24, 'deg': 100, 'gust': 4.47}, 'clouds': {'all': 40}, 'dt': 1744215613, 'sys': {'type': 2, 'id': 2008548, 'country': 'US', 'sunrise': 1744205709, 'sunset': 1744253324}, 'timezone': -25200, 'id': 5746545, 'name': 'Portland', 'cod': 200}
[2025-04-09T16:28:04.634+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 114, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py", line 412, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 64, in transform_load_data
    df_data.to_csv(f"s3://etll/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2178, in close
    self.flush(force=True)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2041, in flush
    if self._upload_chunk(final=force) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2451, in _upload_chunk
    self.commit()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2476, in commit
    write_result = self._call_s3("put_object", **kw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2311, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 371, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 146, in _error_wrapper
    raise err
PermissionError: The provided token has expired.
[2025-04-09T16:28:04.680+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T16:28:04.681+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 16:28:04.183354+00:00 end:2025-04-09 16:28:04.679724+00:00 duration:0.49637
[2025-04-09T16:28:04.681+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_load_weather_data> dag:<DAG: weather_dag> dagrun:<DagRun weather_dag @ 2025-04-09 16:27:42.829062+00:00: manual__2025-04-09T16:27:42.829062+00:00, state:running, queued_at: 2025-04-09 16:27:42.843289+00:00. externally triggered: True>
[2025-04-09T16:28:04.682+0000] {logging_mixin.py:190} INFO - Failure caused by The provided token has expired.
[2025-04-09T16:28:04.682+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2025-04-09T16:27:42.829062+00:00, execution_date=20250409T162742, start_date=20250409T162804, end_date=20250409T162804
[2025-04-09T16:28:04.974+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T16:28:04.975+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task transform_load_weather_data (The provided token has expired.; 32977)
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 114, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py", line 412, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 64, in transform_load_data
    df_data.to_csv(f"s3://etll/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2178, in close
    self.flush(force=True)
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 2041, in flush
    if self._upload_chunk(final=force) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2451, in _upload_chunk
    self.commit()
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2476, in commit
    write_result = self._call_s3("put_object", **kw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2311, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 371, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 146, in _error_wrapper
    raise err
PermissionError: The provided token has expired.
[2025-04-09T16:28:05.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T16:28:05.023+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T16:28:05.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
