[2025-04-09T15:03:45.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T15:03:45.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [queued]>
[2025-04-09T15:03:45.278+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [queued]>
[2025-04-09T15:03:45.278+0000] {taskinstance.py:2867} INFO - Starting attempt 8 of 3
[2025-04-09T15:03:45.300+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-04-09 13:18:29.078083+00:00
[2025-04-09T15:03:45.308+0000] {standard_task_runner.py:72} INFO - Started process 27855 to run task
[2025-04-09T15:03:45.316+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-04-09T13:18:29.078083+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp03f5lrks']
[2025-04-09T15:03:45.317+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask is_weather_api_ready
[2025-04-09T15:03:45.368+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T15:03:45.482+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T13:18:29.078083+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T13:18:29.078083+00:00'
[2025-04-09T15:03:45.486+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T15:03:45.486+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T15:03:45.487+0000] {logging_mixin.py:190} INFO - Current task name:is_weather_api_ready state:running start_date:2025-04-09 15:03:45.270763+00:00
[2025-04-09T15:03:45.487+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T15:03:45.490+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T15:03:45.490+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-09T15:03:45.491+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:03:45.510+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:03:45.628+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:03:45.628+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:04:45.629+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:04:45.632+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:04:45.727+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:04:45.728+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:05:45.728+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:05:45.735+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:05:45.827+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:05:45.827+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:06:45.828+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:06:45.832+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:06:45.923+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:06:45.924+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:07:45.924+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:07:45.927+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:07:46.011+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:07:46.012+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:08:46.013+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:08:46.016+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:08:46.102+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:08:46.102+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:09:46.103+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:09:46.108+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:09:46.197+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:09:46.197+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:10:46.198+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:10:46.201+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:10:46.283+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:10:46.284+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:11:46.284+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:11:46.288+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:11:46.371+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:11:46.371+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:12:46.372+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:12:46.376+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:12:46.480+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:12:46.481+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:13:46.482+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:13:46.485+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:13:46.584+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:13:46.585+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:14:46.586+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:14:46.590+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:14:46.699+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:14:46.700+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:15:46.702+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:15:46.707+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:15:46.814+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:15:46.814+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:16:46.815+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:16:46.821+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:16:46.906+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:16:46.906+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:17:46.907+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:17:46.911+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:17:47.019+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:17:47.019+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:18:47.020+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:18:47.023+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:18:47.111+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:18:47.111+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:19:47.112+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:19:47.115+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:19:47.197+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:19:47.197+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:20:47.198+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:20:47.204+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:20:47.315+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:20:47.316+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:21:47.316+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:21:47.320+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:21:47.414+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:21:47.415+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:22:47.416+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:22:47.421+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:22:47.526+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:22:47.527+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:23:47.528+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:23:47.532+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:23:47.625+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:23:47.626+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:24:47.627+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:24:47.633+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:24:47.736+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:24:47.737+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:25:47.742+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:25:47.745+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:25:47.831+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:25:47.831+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:26:47.832+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:26:47.837+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:26:47.928+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:26:47.928+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:27:47.929+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:27:47.935+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:27:48.031+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:27:48.031+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:28:48.032+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:28:48.036+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:28:48.120+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:28:48.120+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:29:48.121+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:29:48.124+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:29:48.206+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:29:48.206+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:30:48.207+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:30:48.210+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:30:48.288+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:30:48.288+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:31:48.289+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:31:48.292+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:31:48.403+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:31:48.403+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:32:48.411+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:32:48.414+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:32:48.514+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:32:48.515+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:33:48.515+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:33:48.519+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:33:48.625+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:33:48.625+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:34:48.626+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:34:48.629+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:34:48.723+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:34:48.723+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:35:48.724+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:35:48.727+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:35:48.815+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:35:48.816+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:36:48.816+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:36:48.820+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:36:48.905+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:36:48.905+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:37:48.906+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:37:48.908+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:37:48.990+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:37:48.990+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:38:48.991+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:38:48.995+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:38:49.082+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:38:49.083+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:39:49.084+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:39:49.086+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:39:49.179+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:39:49.179+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:40:49.180+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:40:49.183+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:40:49.269+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:40:49.270+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:41:49.271+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:41:49.274+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:41:49.362+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:41:49.363+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:42:49.364+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:42:49.372+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:42:49.458+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:42:49.458+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:43:49.459+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:43:49.462+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:43:49.562+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:43:49.563+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:44:49.564+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:44:49.570+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:44:49.672+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:44:49.672+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:45:49.673+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:45:49.675+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:45:49.772+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:45:49.773+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:46:49.774+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:46:49.782+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:46:49.882+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:46:49.882+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:47:49.883+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:47:49.890+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:47:49.990+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:47:49.991+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:48:49.993+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:48:50.007+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:48:50.103+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:48:50.103+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:49:50.104+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:49:50.107+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:49:50.213+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:49:50.213+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:50:50.214+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:50:50.218+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:50:50.322+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:50:50.322+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:51:50.323+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:51:50.327+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:51:50.442+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:51:50.442+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:52:50.443+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:52:50.446+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:52:50.555+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:52:50.555+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:53:50.556+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:53:50.559+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:53:50.654+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:53:50.654+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:54:50.655+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:54:50.658+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:54:50.745+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:54:50.746+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:55:50.746+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:55:50.749+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:55:50.850+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:55:50.850+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:56:50.851+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:56:50.856+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:56:50.951+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:56:50.951+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:57:50.952+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:57:50.958+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:57:51.051+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:57:51.051+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:58:51.052+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:58:51.054+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:58:51.152+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:58:51.152+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:59:51.153+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:59:51.156+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:59:51.258+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:59:51.258+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:00:51.259+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:00:51.262+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:00:51.352+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:00:51.352+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:01:51.353+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:01:51.358+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:01:51.450+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:01:51.450+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:02:51.451+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:02:51.455+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:02:51.539+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:02:51.539+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:03:51.540+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:03:51.544+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:03:51.630+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:03:51.630+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:04:51.632+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:04:51.635+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:04:51.721+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:04:51.721+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:05:51.722+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:05:51.726+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:05:51.827+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:05:51.827+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:06:51.828+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:06:51.831+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:06:51.923+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:06:51.923+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:07:51.924+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:07:51.927+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:07:52.017+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:07:52.018+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:08:52.018+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:08:52.022+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:08:52.129+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:08:52.130+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:09:52.131+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:09:52.134+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:09:52.236+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:09:52.237+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:10:52.238+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:10:52.241+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:10:52.340+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:10:52.341+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:11:52.341+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:11:52.344+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:11:52.455+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:11:52.455+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:12:52.456+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:12:52.459+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:12:52.546+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:12:52.547+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:13:52.547+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:13:52.550+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:13:52.636+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:13:52.636+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:14:52.637+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:14:52.643+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:14:52.726+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:14:52.726+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:15:52.727+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:15:52.730+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:15:52.818+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:15:52.818+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:16:52.819+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:16:52.832+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:16:52.918+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:16:52.919+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:17:52.920+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:17:52.922+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:17:53.008+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:17:53.009+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:18:53.010+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:18:53.019+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:18:53.111+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:18:53.111+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:19:53.112+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:19:53.116+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:19:53.201+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:19:53.201+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:20:53.202+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:20:53.212+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:20:53.316+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:20:53.316+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:21:53.317+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:21:53.319+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:21:53.397+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:21:53.398+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:22:53.398+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:22:53.405+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:22:53.489+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:22:53.490+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:23:53.491+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:23:53.501+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:23:53.588+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:23:53.589+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:24:53.589+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:24:53.592+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:24:53.690+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:24:53.690+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:25:53.691+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:25:53.702+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:25:53.811+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:25:53.812+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:26:53.812+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:26:53.816+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:26:53.921+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:26:53.922+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:27:53.923+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:27:53.928+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:27:54.025+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:27:54.025+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:28:54.026+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:28:54.031+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:28:54.114+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:28:54.114+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:29:54.115+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:29:54.118+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:29:54.207+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:29:54.207+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:30:54.209+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:30:54.212+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:30:54.301+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:30:54.301+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:31:54.302+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:31:54.305+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:31:54.392+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:31:54.392+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:32:54.393+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:32:54.396+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:32:54.481+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:32:54.482+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:33:54.483+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:33:54.486+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:33:54.588+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:33:54.588+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:34:54.589+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:34:54.593+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:34:54.683+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:34:54.684+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:35:54.685+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:35:54.688+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:35:54.777+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:35:54.778+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:36:54.778+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:36:54.782+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:36:54.868+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:36:54.868+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:37:54.869+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:37:54.873+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:37:54.961+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:37:54.962+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:38:54.962+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:38:54.965+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:38:55.059+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:38:55.060+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:39:55.060+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:39:55.066+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:39:55.154+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:39:55.154+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:40:55.155+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:40:55.158+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:40:55.255+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:40:55.255+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:41:55.256+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:41:55.261+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:41:55.361+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:41:55.361+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:42:55.362+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:42:55.366+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:42:55.468+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:42:55.468+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:43:55.469+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:43:55.472+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:43:55.576+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:43:55.576+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:44:55.577+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:44:55.581+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:44:55.672+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:44:55.672+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:45:55.673+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:45:55.676+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:45:55.775+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:45:55.775+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:46:55.776+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:46:55.779+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:46:55.869+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:46:55.870+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:47:55.884+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:47:55.889+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:47:55.982+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:47:55.982+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:48:55.983+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:48:55.987+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:48:56.091+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:48:56.091+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:49:56.092+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:49:56.100+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:49:56.206+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:49:56.207+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:50:56.208+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:50:56.211+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:50:56.315+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:50:56.315+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:51:56.316+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:51:56.322+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:51:56.414+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:51:56.415+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:52:56.416+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:52:56.421+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:52:56.501+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:52:56.501+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:53:56.502+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:53:56.510+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:53:56.594+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:53:56.595+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:54:56.596+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:54:56.600+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:54:56.681+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:54:56.681+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:55:56.682+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:55:56.685+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:55:56.785+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:55:56.786+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:56:56.787+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:56:56.790+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:56:56.877+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:56:56.877+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:57:56.878+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:57:56.882+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:57:56.963+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:57:56.963+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:58:56.965+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:58:56.972+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:58:57.067+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:58:57.068+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:59:57.069+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:59:57.074+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:59:57.167+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:59:57.167+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:00:57.168+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:00:57.172+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:00:57.279+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:00:57.279+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:01:57.280+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:01:57.286+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:01:57.383+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:01:57.383+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:02:57.384+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:02:57.389+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:02:57.490+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:02:57.490+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:03:57.491+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:03:57.498+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:03:57.603+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:03:57.603+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:04:57.605+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:04:57.610+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:04:57.715+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:04:57.717+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:05:57.719+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:05:57.722+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:05:57.805+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:05:57.805+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:06:57.806+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:06:57.813+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:06:57.898+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:06:57.898+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:07:57.900+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:07:57.905+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:07:57.995+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:07:57.995+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:08:57.996+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:08:58.005+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:08:58.101+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:08:58.101+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:09:58.102+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:09:58.105+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:09:58.194+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:09:58.194+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:10:58.196+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:10:58.198+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:10:58.303+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:10:58.304+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:11:58.305+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:11:58.310+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:11:58.402+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:11:58.402+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:12:58.404+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:12:58.408+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:12:58.516+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:12:58.516+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:13:58.517+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:13:58.520+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:13:58.615+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:13:58.615+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:14:58.616+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:14:58.619+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:14:58.717+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:14:58.717+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:15:58.718+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:15:58.721+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:15:58.815+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:15:58.815+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:16:58.816+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:16:58.822+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:16:58.913+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:16:58.913+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:17:58.914+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:17:58.918+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:17:59.011+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:17:59.011+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:18:59.012+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:18:59.015+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:18:59.118+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:18:59.118+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:19:59.119+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:19:59.122+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:19:59.224+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:19:59.225+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:20:59.225+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:20:59.229+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:20:59.320+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:20:59.320+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:21:59.321+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:21:59.325+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:21:59.429+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:21:59.429+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:22:59.430+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:22:59.433+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:22:59.537+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:22:59.537+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:23:59.538+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:23:59.541+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:23:59.632+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:23:59.632+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:24:59.633+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:24:59.636+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:24:59.726+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:24:59.726+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:25:59.728+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:25:59.731+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:25:59.844+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:25:59.845+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:26:59.846+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:26:59.848+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:26:59.946+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:26:59.946+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:27:59.947+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:27:59.950+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:28:00.051+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:28:00.051+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:29:00.052+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:29:00.060+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:29:00.160+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:29:00.160+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:30:00.161+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:30:00.164+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:30:00.250+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:30:00.251+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:31:00.251+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:31:00.255+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:31:00.341+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:31:00.341+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:32:00.342+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:32:00.345+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:32:00.428+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:32:00.429+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:33:00.429+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:33:00.432+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:33:00.530+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:33:00.531+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:34:00.531+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:34:00.535+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:34:00.643+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:34:00.643+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:35:00.645+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:35:00.647+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:35:00.748+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:35:00.748+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:36:00.749+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:36:00.752+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:36:00.854+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:36:00.854+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:37:00.855+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:37:00.858+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:37:00.960+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:37:00.960+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:38:00.961+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:38:00.963+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:38:01.053+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:38:01.053+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:39:01.054+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:39:01.057+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:39:01.164+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:39:01.164+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:40:01.165+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:40:01.169+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:40:01.259+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:40:01.260+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:41:01.261+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:41:01.263+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:41:01.365+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:41:01.365+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:42:01.367+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:42:01.370+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:42:01.454+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:42:01.455+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:43:01.456+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:43:01.463+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:43:01.545+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:43:01.545+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:44:01.546+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:44:01.553+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:44:01.639+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:44:01.639+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:45:01.640+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:45:01.644+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:45:01.733+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:45:01.734+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:46:01.735+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:46:01.737+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:46:01.822+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:46:01.823+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:47:01.823+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:47:01.826+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:47:01.918+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:47:01.919+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:48:01.920+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:48:01.923+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:48:02.008+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:48:02.009+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:49:02.009+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:49:02.013+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:49:02.098+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:49:02.098+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:50:02.100+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:50:02.104+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:50:02.192+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:50:02.193+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:51:02.194+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:51:02.204+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:51:02.283+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:51:02.283+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:52:02.284+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:52:02.288+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:52:02.367+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:52:02.368+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:53:02.368+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:53:02.372+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:53:02.461+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:53:02.461+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:54:02.462+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:54:02.465+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:54:02.552+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:54:02.553+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:55:02.562+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:55:02.566+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:55:02.652+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:55:02.655+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:56:02.656+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:56:02.658+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:56:02.743+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:56:02.743+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:57:02.744+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:57:02.748+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:57:02.837+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:57:02.838+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
