[2025-04-09T13:43:01.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T13:43:01.103+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [queued]>
[2025-04-09T13:43:01.112+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [queued]>
[2025-04-09T13:43:01.113+0000] {taskinstance.py:2867} INFO - Starting attempt 7 of 3
[2025-04-09T13:43:01.136+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-04-09 13:18:29.078083+00:00
[2025-04-09T13:43:01.148+0000] {standard_task_runner.py:72} INFO - Started process 25456 to run task
[2025-04-09T13:43:01.155+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-04-09T13:18:29.078083+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpfzu5xbkl']
[2025-04-09T13:43:01.156+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask is_weather_api_ready
[2025-04-09T13:43:01.215+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:18:29.078083+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T13:43:01.342+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T13:18:29.078083+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T13:18:29.078083+00:00'
[2025-04-09T13:43:01.344+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T13:43:01.344+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T13:43:01.344+0000] {logging_mixin.py:190} INFO - Current task name:is_weather_api_ready state:running start_date:2025-04-09 13:43:01.104114+00:00
[2025-04-09T13:43:01.345+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T13:43:01.345+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T13:43:01.345+0000] {baseoperator.py:423} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-04-09T13:43:01.346+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:43:01.354+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:43:01.472+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:43:01.473+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:44:01.474+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:44:01.478+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:44:01.578+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:44:01.578+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:45:01.579+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:45:01.583+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:45:01.678+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:45:01.679+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:46:01.680+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:46:01.683+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:46:01.781+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:46:01.781+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:47:01.782+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:47:01.785+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:47:01.873+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:47:01.874+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:48:01.874+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:48:01.877+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:48:01.965+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:48:01.965+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:49:01.966+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:49:01.973+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:49:02.064+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:49:02.065+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:50:02.065+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:50:02.068+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:50:02.157+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:50:02.159+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:51:02.160+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:51:02.163+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:51:02.249+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:51:02.249+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:52:02.250+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:52:02.254+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:52:02.341+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:52:02.341+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:53:02.342+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:53:02.346+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:53:02.427+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:53:02.428+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:54:02.428+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:54:02.432+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:54:02.518+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:54:02.519+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:55:02.520+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:55:02.522+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:55:02.608+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:55:02.609+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:56:02.610+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:56:02.613+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:56:02.701+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:56:02.701+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:57:02.702+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:57:02.705+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:57:02.788+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:57:02.789+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:58:02.789+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:58:02.792+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:58:02.880+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:58:02.880+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T13:59:02.882+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T13:59:02.885+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T13:59:02.975+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T13:59:02.976+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:00:02.977+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:00:02.980+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:00:03.070+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:00:03.071+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:01:03.071+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:01:03.076+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:01:03.166+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:01:03.167+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:02:03.167+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:02:03.173+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:02:03.261+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:02:03.262+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:03:03.263+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:03:03.266+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:03:03.440+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:03:03.441+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:04:03.442+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:04:03.446+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:04:03.536+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:04:03.537+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:05:03.538+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:05:03.541+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:05:03.635+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:05:03.636+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:06:03.637+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:06:03.642+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:06:03.728+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:06:03.728+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:07:03.729+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:07:03.731+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:07:03.834+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:07:03.835+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:08:03.836+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:08:03.840+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:08:03.940+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:08:03.940+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:09:03.941+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:09:03.944+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:09:04.043+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:09:04.043+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:10:04.044+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:10:04.050+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:10:04.151+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:10:04.152+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:11:04.153+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:11:04.156+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:11:04.257+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:11:04.258+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:12:04.258+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:12:04.261+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:12:04.363+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:12:04.364+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:13:04.364+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:13:04.372+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:13:04.473+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:13:04.473+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:14:04.475+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:14:04.479+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:14:04.578+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:14:04.578+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:15:04.579+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:15:04.582+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:15:04.676+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:15:04.677+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:16:04.677+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:16:04.681+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:16:04.773+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:16:04.773+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:17:04.774+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:17:04.777+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:17:04.880+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:17:04.880+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:18:04.881+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:18:04.889+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:18:04.981+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:18:04.982+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:19:04.984+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:19:04.987+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:19:05.084+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:19:05.084+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:20:05.087+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:20:05.090+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:20:05.189+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:20:05.189+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:21:05.190+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:21:05.199+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:21:05.291+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:21:05.292+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:22:05.292+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:22:05.296+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:22:05.385+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:22:05.385+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:23:05.386+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:23:05.391+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:23:05.482+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:23:05.482+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:24:05.483+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:24:05.486+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:24:05.579+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:24:05.580+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:25:05.580+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:25:05.584+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:25:05.669+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:25:05.670+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:26:05.671+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:26:05.674+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:26:05.758+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:26:05.759+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:27:05.760+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:27:05.763+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:27:05.850+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:27:05.851+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:28:05.851+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:28:05.856+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:28:05.945+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:28:05.946+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:29:05.946+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:29:05.951+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:29:06.031+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:29:06.031+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:30:06.033+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:30:06.036+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:30:06.120+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:30:06.121+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:31:06.122+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:31:06.125+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:31:06.214+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:31:06.215+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:32:06.216+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:32:06.218+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:32:06.298+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:32:06.298+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:33:06.299+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:33:06.302+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:33:06.404+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:33:06.404+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:34:06.405+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:34:06.408+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:34:06.495+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:34:06.495+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:35:06.497+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:35:06.500+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:35:06.588+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:35:06.588+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:36:06.590+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:36:06.599+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:36:06.684+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:36:06.684+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:37:06.685+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:37:06.689+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:37:06.792+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:37:06.793+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:38:06.795+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:38:06.798+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:38:06.890+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:38:06.890+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:39:06.892+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:39:06.894+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:39:06.990+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:39:06.990+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:40:06.991+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:40:06.994+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:40:07.098+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:40:07.098+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:41:07.099+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:41:07.102+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:41:07.202+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:41:07.202+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:42:07.203+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:42:07.207+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:42:07.300+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:42:07.300+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:43:07.301+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:43:07.306+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:43:07.399+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:43:07.400+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:44:07.400+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:44:07.404+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:44:07.488+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:44:07.488+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:45:07.489+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:45:07.494+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:45:07.580+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:45:07.580+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:46:07.581+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:46:07.584+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:46:07.673+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:46:07.673+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:47:07.674+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:47:07.678+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:47:07.761+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:47:07.761+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:48:07.763+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:48:07.768+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:48:07.855+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:48:07.855+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:49:07.856+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:49:07.860+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:49:07.949+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:49:07.949+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:50:07.950+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:50:07.954+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:50:08.056+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:50:08.057+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:51:08.057+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:51:08.061+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:51:08.163+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:51:08.164+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:52:08.164+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:52:08.167+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:52:08.275+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:52:08.276+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:53:08.276+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:53:08.279+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:53:08.379+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:53:08.379+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:54:08.380+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:54:08.383+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:54:08.490+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:54:08.491+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:55:08.492+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:55:08.495+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:55:08.597+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:55:08.598+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:56:08.599+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:56:08.603+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:56:08.700+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:56:08.700+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:57:08.701+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:57:08.704+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:57:08.808+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:57:08.808+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:58:08.809+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:58:08.814+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:58:08.921+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:58:08.921+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T14:59:08.922+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T14:59:08.925+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T14:59:09.023+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T14:59:09.024+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:00:09.024+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:00:09.027+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:00:09.119+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:00:09.120+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:01:09.120+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:01:09.127+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:01:09.227+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:01:09.227+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:02:09.228+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:02:09.231+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:02:09.327+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:02:09.328+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:03:09.328+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:03:09.331+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:03:09.434+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:03:09.434+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:04:09.435+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:04:09.440+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:04:09.530+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:04:09.530+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:05:09.531+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:05:09.533+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:05:09.621+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:05:09.621+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:06:09.622+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:06:09.626+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:06:09.710+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:06:09.710+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:07:09.711+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:07:09.714+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:07:09.796+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:07:09.797+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:08:09.797+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:08:09.800+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:08:09.905+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:08:09.905+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:09:09.910+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:09:09.915+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:09:10.001+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:09:10.001+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:10:10.002+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:10:10.006+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:10:10.092+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:10:10.093+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:11:10.093+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:11:10.098+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:11:10.184+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:11:10.185+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:12:10.186+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:12:10.190+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:12:10.284+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:12:10.286+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:13:10.287+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:13:10.290+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:13:10.391+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:13:10.392+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:14:10.392+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:14:10.395+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:14:10.500+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:14:10.500+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:15:10.501+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:15:10.505+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:15:10.595+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:15:10.596+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:16:10.598+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:16:10.603+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:16:10.709+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:16:10.709+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:17:10.710+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:17:10.713+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:17:10.799+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:17:10.799+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:18:10.800+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:18:10.803+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:18:10.886+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:18:10.887+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:19:10.887+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:19:10.894+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:19:10.980+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:19:10.981+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:20:10.982+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:20:10.985+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:20:11.084+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:20:11.084+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:21:11.086+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:21:11.090+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:21:11.184+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:21:11.184+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:22:11.187+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:22:11.190+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:22:11.278+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:22:11.278+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:23:11.279+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:23:11.282+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:23:11.393+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:23:11.393+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:24:11.398+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:24:11.401+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:24:11.501+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:24:11.502+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:25:11.502+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:25:11.505+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:25:11.605+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:25:11.605+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:26:11.606+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:26:11.610+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:26:11.699+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:26:11.700+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:27:11.700+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:27:11.705+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:27:11.788+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:27:11.788+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:28:11.789+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:28:11.792+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:28:11.874+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:28:11.878+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:29:11.879+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:29:11.885+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:29:11.971+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:29:11.972+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:30:11.973+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:30:11.976+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:30:12.057+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:30:12.058+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:31:12.059+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:31:12.062+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:31:12.149+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:31:12.149+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:32:12.150+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:32:12.153+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:32:12.256+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:32:12.256+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:33:12.257+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:33:12.262+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:33:12.364+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:33:12.364+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:34:12.365+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:34:12.371+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:34:12.480+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:34:12.480+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:35:12.481+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:35:12.484+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:35:12.582+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:35:12.583+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:36:12.584+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:36:12.588+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:36:12.667+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:36:12.667+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:37:12.668+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:37:12.672+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:37:12.760+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:37:12.760+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:38:12.761+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:38:12.769+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:38:12.854+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:38:12.855+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:39:12.856+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:39:12.858+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:39:12.950+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:39:12.951+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:40:12.951+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:40:12.954+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:40:13.041+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:40:13.041+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:41:13.042+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:41:13.050+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:41:13.150+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:41:13.151+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:42:13.152+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:42:13.155+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:42:13.241+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:42:13.241+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:43:13.242+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:43:13.246+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:43:13.345+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:43:13.345+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:44:13.346+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:44:13.349+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:44:13.441+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:44:13.441+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:45:13.442+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:45:13.445+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:45:13.540+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:45:13.541+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:46:13.542+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:46:13.545+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:46:13.645+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:46:13.645+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:47:13.646+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:47:13.653+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:47:13.757+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:47:13.757+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:48:13.758+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:48:13.761+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:48:13.843+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:48:13.844+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:49:13.845+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:49:13.847+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:49:13.932+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:49:13.932+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:50:13.933+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:50:13.936+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:50:14.038+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:50:14.038+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:51:14.039+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:51:14.043+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:51:14.149+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:51:14.149+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:52:14.150+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:52:14.154+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:52:14.253+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:52:14.254+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:53:14.254+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:53:14.258+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:53:14.357+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:53:14.357+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:54:14.358+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:54:14.361+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:54:14.448+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:54:14.449+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:55:14.449+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:55:14.452+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:55:14.540+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:55:14.540+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:56:14.541+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:56:14.545+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:56:14.647+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:56:14.648+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:57:14.649+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:57:14.652+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:57:14.756+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:57:14.756+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:58:14.757+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:58:14.760+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:58:14.864+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:58:14.865+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T15:59:14.866+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T15:59:14.868+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:59:14.978+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T15:59:14.978+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:00:14.979+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:00:14.982+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:00:15.081+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:00:15.081+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:01:15.082+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:01:15.085+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:01:15.173+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:01:15.174+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:02:15.175+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:02:15.178+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:02:15.264+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:02:15.264+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:03:15.265+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:03:15.271+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:03:15.359+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:03:15.360+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:04:15.361+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:04:15.364+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:04:15.448+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:04:15.449+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:05:15.449+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:05:15.453+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:05:15.545+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:05:15.546+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:06:15.547+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:06:15.550+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:06:15.652+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:06:15.652+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:07:15.653+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:07:15.657+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:07:15.750+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:07:15.750+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:08:15.752+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:08:15.760+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:08:15.866+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:08:15.866+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:09:15.867+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:09:15.870+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:09:15.977+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:09:15.978+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:10:15.978+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:10:15.986+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:10:16.090+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:10:16.090+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:11:16.091+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:11:16.095+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:11:16.200+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:11:16.200+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:12:16.201+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:12:16.205+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:12:16.305+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:12:16.306+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:13:16.307+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:13:16.310+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:13:16.394+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:13:16.395+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:14:16.396+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:14:16.402+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:14:16.489+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:14:16.490+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:15:16.491+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:15:16.494+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:15:16.580+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:15:16.580+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:16:16.581+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:16:16.588+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:16:16.676+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:16:16.676+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:17:16.677+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:17:16.680+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:17:16.764+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:17:16.765+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:18:16.765+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:18:16.769+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:18:16.858+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:18:16.858+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:19:16.860+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:19:16.864+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:19:16.952+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:19:16.953+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:20:16.954+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:20:16.959+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:20:17.045+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:20:17.046+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:21:17.047+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:21:17.050+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:21:17.134+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:21:17.134+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:22:17.135+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:22:17.138+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:22:17.226+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:22:17.227+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:23:17.230+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:23:17.233+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:23:17.317+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:23:17.317+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:24:17.318+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:24:17.321+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:24:17.408+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:24:17.408+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:25:17.409+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:25:17.413+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:25:17.501+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:25:17.502+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:26:17.505+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:26:17.509+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:26:17.612+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:26:17.613+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:27:17.615+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:27:17.617+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:27:17.706+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:27:17.706+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:28:17.709+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:28:17.712+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:28:17.791+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:28:17.791+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:29:17.792+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:29:17.797+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:29:17.882+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:29:17.883+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:30:17.884+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:30:17.894+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:30:17.979+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:30:17.979+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:31:17.980+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:31:17.985+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:31:18.074+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:31:18.077+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:32:18.084+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:32:18.087+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:32:18.169+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:32:18.169+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:33:18.170+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:33:18.174+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:33:18.260+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:33:18.260+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:34:18.261+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:34:18.264+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:34:18.358+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:34:18.358+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:35:18.359+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:35:18.361+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:35:18.463+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:35:18.463+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:36:18.465+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:36:18.477+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:36:18.564+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:36:18.564+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:37:18.565+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:37:18.580+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:37:18.661+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:37:18.661+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:38:18.662+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:38:18.669+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:38:18.756+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:38:18.758+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:39:18.763+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:39:18.767+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:39:18.856+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:39:18.857+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:40:18.857+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:40:18.861+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:40:18.946+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:40:18.946+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:41:18.948+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:41:18.950+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:41:19.059+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:41:19.059+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:42:19.061+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:42:19.064+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:42:19.169+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:42:19.170+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:43:19.170+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:43:19.176+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:43:19.282+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:43:19.283+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:44:19.284+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:44:19.293+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:44:19.390+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:44:19.390+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:45:19.391+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:45:19.395+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:45:19.488+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:45:19.489+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:46:19.489+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:46:19.492+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:46:19.572+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:46:19.572+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:47:19.573+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:47:19.576+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:47:19.659+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:47:19.659+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:48:19.660+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:48:19.664+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:48:19.763+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:48:19.763+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:49:19.764+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:49:19.766+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:49:19.873+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:49:19.873+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:50:19.874+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:50:19.877+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:50:19.967+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:50:19.967+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:51:19.968+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:51:19.972+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:51:20.061+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:51:20.061+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:52:20.062+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:52:20.065+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:52:20.154+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:52:20.155+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:53:20.158+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:53:20.165+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:53:20.257+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:53:20.258+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:54:20.259+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:54:20.262+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:54:20.348+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:54:20.348+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:55:20.349+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:55:20.354+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:55:20.440+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:55:20.440+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:56:20.441+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:56:20.447+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:56:20.538+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:56:20.539+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:57:20.540+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:57:20.547+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:57:20.637+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:57:20.637+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:58:20.638+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:58:20.642+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:58:20.725+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:58:20.725+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T16:59:20.726+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T16:59:20.737+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T16:59:20.831+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T16:59:20.832+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:00:20.833+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:00:20.836+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:00:20.924+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:00:20.924+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:01:20.925+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:01:20.928+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:01:21.032+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:01:21.033+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:02:21.033+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:02:21.036+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:02:21.135+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:02:21.136+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:03:21.137+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:03:21.140+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:03:21.229+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:03:21.229+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:04:21.230+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:04:21.233+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:04:21.332+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:04:21.333+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:05:21.333+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:05:21.341+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:05:21.433+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:05:21.433+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:06:21.434+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:06:21.437+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:06:21.527+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:06:21.527+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:07:21.528+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:07:21.531+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:07:21.613+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:07:21.614+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:08:21.616+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:08:21.619+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:08:21.707+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:08:21.709+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:09:21.711+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:09:21.713+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:09:21.804+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:09:21.804+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:10:21.805+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:10:21.809+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:10:21.892+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:10:21.892+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:11:21.895+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:11:21.899+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:11:22.006+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:11:22.006+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:12:22.008+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:12:22.011+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:12:22.110+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:12:22.110+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:13:22.111+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:13:22.116+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:13:22.213+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:13:22.213+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:14:22.217+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:14:22.229+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:14:22.328+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:14:22.329+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:15:22.329+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:15:22.335+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:15:22.440+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:15:22.441+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:16:22.442+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:16:22.445+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:16:22.544+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:16:22.544+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:17:22.545+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:17:22.549+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:17:22.640+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:17:22.641+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:18:22.642+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:18:22.646+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:18:22.747+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:18:22.747+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:19:22.748+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:19:22.751+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:19:22.851+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:19:22.851+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:20:22.852+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:20:22.857+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:20:22.963+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:20:22.963+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:21:22.964+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:21:22.968+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:21:23.076+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:21:23.080+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:22:23.082+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:22:23.085+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:22:23.182+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:22:23.182+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:23:23.183+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:23:23.186+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:23:23.280+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:23:23.280+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:24:23.281+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:24:23.284+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:24:23.387+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:24:23.387+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:25:23.388+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:25:23.392+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:25:23.496+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:25:23.496+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:26:23.497+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:26:23.500+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:26:23.588+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:26:23.589+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:27:23.590+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:27:23.592+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:27:23.690+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:27:23.691+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:28:23.692+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:28:23.695+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:28:23.793+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:28:23.794+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:29:23.794+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:29:23.797+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:29:23.892+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:29:23.892+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:30:23.894+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:30:23.897+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:30:23.994+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:30:23.995+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:31:23.995+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:31:23.999+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:31:24.087+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:31:24.087+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:32:24.088+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:32:24.094+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:32:24.179+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:32:24.179+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:33:24.180+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:33:24.184+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:33:24.272+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:33:24.272+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:34:24.273+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:34:24.276+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:34:24.381+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:34:24.382+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:35:24.383+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:35:24.387+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:35:24.485+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:35:24.485+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:36:24.486+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:36:24.489+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:36:24.584+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:36:24.584+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:37:24.585+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:37:24.589+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:37:24.688+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:37:24.688+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:38:24.689+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:38:24.692+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:38:24.797+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:38:24.797+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:39:24.800+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:39:24.804+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:39:24.890+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:39:24.891+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:40:24.891+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:40:24.897+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:40:24.986+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:40:24.986+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:41:24.988+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:41:24.991+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:41:25.084+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:41:25.084+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:42:25.085+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:42:25.088+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:42:25.175+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:42:25.176+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:43:25.177+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:43:25.180+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:43:25.263+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:43:25.264+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:44:25.265+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:44:25.267+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:44:25.351+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:44:25.352+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:45:25.352+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:45:25.356+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:45:25.440+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:45:25.441+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:46:25.442+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:46:25.445+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:46:25.552+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:46:25.552+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:47:25.553+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:47:25.557+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:47:25.641+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:47:25.642+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:48:25.644+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:48:25.646+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:48:25.730+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:48:25.730+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:49:25.731+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:49:25.736+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:49:25.824+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:49:25.825+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:50:25.826+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:50:25.829+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:50:25.926+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:50:25.927+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:51:25.928+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:51:25.935+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:51:26.015+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:51:26.016+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:52:26.017+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:52:26.024+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:52:26.116+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:52:26.116+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:53:26.120+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:53:26.127+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:53:26.212+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:53:26.213+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:54:26.213+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:54:26.217+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:54:26.298+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:54:26.298+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:55:26.299+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:55:26.305+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:55:26.389+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:55:26.389+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:56:26.390+0000] {http.py:145} INFO - Poking: /data/S2.5/weather?q=Portland&APPID=4d13f07efe491003cd53c704f189b00f
[2025-04-09T17:56:26.393+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T17:56:26.480+0000] {http.py:278} ERROR - HTTP error: Not Found
[2025-04-09T17:56:26.481+0000] {http.py:279} ERROR - {"cod":"404","message":"Internal error"}
[2025-04-09T17:57:06.697+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
